name: Deploy Flask App to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Copy files to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        source: "."
        target: "~/SVMS"

    - name: Run deployment script on EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd ~/SVMS
          python3 -m venv venv || true
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          sudo lsof -ti :5000 | xargs -r sudo kill -9
          sudo systemctl daemon-reload
          sudo systemctl restart svms.service
